print('=-='*15)
print('------------------TABUADA-------------------')
print('=-='*15)
num = int(input('Digite o número que você quer saber a tabuada: '))
print(f'{num} X {1:2} = {num*1}')
print(f'{num} X {2:2} = {num*2}')
print(f'{num} X {3:2} = {num*3}')
print(f'{num} X {4:2} = {num*4}')
print(f'{num} X {5:2} = {num*5}')
print(f'{num} X {6:2} = {num*6}')
print(f'{num} X {7:2} = {num*7}')
print(f'{num} X {8:2} = {num*8}')
print(f'{num} X {9:2} = {num*9}')
print(f'{num} X {10:2} = {num*10}')

